// Dados mockados do projeto Monitoramento Inteligente de Grama — CCR Motiva
// Esses dados simulam o que futuramente virá de uma API real

export const trechos = [
  {
    id: '1',
    rodovia: 'SP-280',
    nomeRodovia: 'Castelo Branco',
    km: 'km 42–43',
    sentido: 'Oeste',
    alturaAtual: 34,
    limite: 30,
    status: 'corte_necessario',
    tipoVegetacao: 'Grama densa',
    clima: 'Chuva recente — crescimento acelerado',
    ultimaColeta: '13/06/2026',
    previsaoCorte: 'Imediato',
    diasAteCorte: 0,
    historico: [
      { data: '02/05', altura: 14 },
      { data: '16/05', altura: 22 },
      { data: '30/05', altura: 28 },
      { data: '13/06', altura: 34 },
    ],
    observacao: 'Histórico de crescimento acelerado pós-chuva.',
  },
  {
    id: '2',
    rodovia: 'SP-280',
    nomeRodovia: 'Castelo Branco',
    km: 'km 47–48',
    sentido: 'Leste',
    alturaAtual: 31,
    limite: 30,
    status: 'corte_necessario',
    tipoVegetacao: 'Capim alto',
    clima: 'Chuva recente — capim cresce rápido',
    ultimaColeta: '13/06/2026',
    previsaoCorte: 'Imediato',
    diasAteCorte: 0,
    historico: [
      { data: '02/05', altura: 12 },
      { data: '16/05', altura: 20 },
      { data: '30/05', altura: 26 },
      { data: '13/06', altura: 31 },
    ],
    observacao: null,
  },
  {
    id: '3',
    rodovia: 'SP-330',
    nomeRodovia: 'Anhanguera',
    km: 'km 98–99',
    sentido: 'Sul',
    alturaAtual: 29,
    limite: 30,
    status: 'atencao',
    tipoVegetacao: 'Grama densa',
    clima: 'Muito úmido — risco em 2 dias',
    ultimaColeta: '14/06/2026',
    previsaoCorte: '17/06/2026',
    diasAteCorte: 2,
    historico: [
      { data: '02/05', altura: 11 },
      { data: '16/05', altura: 19 },
      { data: '30/05', altura: 24 },
      { data: '14/06', altura: 29 },
    ],
    observacao: 'Próximo a área de drenagem, solo retém mais umidade.',
  },
  {
    id: '4',
    rodovia: 'SP-330',
    nomeRodovia: 'Anhanguera',
    km: 'km 112–113',
    sentido: 'Norte',
    alturaAtual: 27,
    limite: 30,
    status: 'atencao',
    tipoVegetacao: 'Capim alto',
    clima: 'Chuva moderada',
    ultimaColeta: '14/06/2026',
    previsaoCorte: '20/06/2026',
    diasAteCorte: 5,
    historico: [
      { data: '02/05', altura: 8 },
      { data: '16/05', altura: 15 },
      { data: '30/05', altura: 20 },
      { data: '14/06', altura: 27 },
    ],
    observacao: null,
  },
  {
    id: '5',
    rodovia: 'SP-348',
    nomeRodovia: 'Bandeirantes',
    km: 'km 88–89',
    sentido: 'Norte',
    alturaAtual: 32,
    limite: 30,
    status: 'corte_necessario',
    tipoVegetacao: 'Capim alto',
    clima: 'Chuva recente — crescimento acelerado',
    ultimaColeta: '15/06/2026',
    previsaoCorte: 'Imediato',
    diasAteCorte: 0,
    historico: [
      { data: '02/05', altura: 13 },
      { data: '16/05', altura: 22 },
      { data: '30/05', altura: 27 },
      { data: '15/06', altura: 32 },
    ],
    observacao: 'Reincidente — 3 ciclos consecutivos acima de 25 cm.',
  },
  {
    id: '6',
    rodovia: 'SP-348',
    nomeRodovia: 'Bandeirantes',
    km: 'km 81–82',
    sentido: 'Norte',
    alturaAtual: 28,
    limite: 30,
    status: 'atencao',
    tipoVegetacao: 'Grama densa',
    clima: 'Chuva recente',
    ultimaColeta: '15/06/2026',
    previsaoCorte: '19/06/2026',
    diasAteCorte: 4,
    historico: [
      { data: '02/05', altura: 10 },
      { data: '16/05', altura: 17 },
      { data: '30/05', altura: 23 },
      { data: '15/06', altura: 28 },
    ],
    observacao: null,
  },
  {
    id: '7',
    rodovia: 'SP-150',
    nomeRodovia: 'Anchieta',
    km: 'km 34–35',
    sentido: 'Sul',
    alturaAtual: 22,
    limite: 30,
    status: 'atencao',
    tipoVegetacao: 'Capim alto',
    clima: 'Muito úmido — próximo ao litoral',
    ultimaColeta: '12/06/2026',
    previsaoCorte: '23/06/2026',
    diasAteCorte: 8,
    historico: [
      { data: '28/04', altura: 10 },
      { data: '12/05', altura: 15 },
      { data: '29/05', altura: 18 },
      { data: '12/06', altura: 22 },
    ],
    observacao: null,
  },
  {
    id: '8',
    rodovia: 'SP-160',
    nomeRodovia: 'Imigrantes',
    km: 'km 15–16',
    sentido: 'Sul',
    alturaAtual: 30,
    limite: 30,
    status: 'corte_necessario',
    tipoVegetacao: 'Grama densa',
    clima: 'Serra do Mar — alta umidade constante',
    ultimaColeta: '11/06/2026',
    previsaoCorte: 'Imediato',
    diasAteCorte: 0,
    historico: [
      { data: '28/04', altura: 13 },
      { data: '12/05', altura: 21 },
      { data: '28/05', altura: 26 },
      { data: '11/06', altura: 30 },
    ],
    observacao: 'Vegetação densa na Serra do Mar, monitorar semanalmente.',
  },
  {
    id: '9',
    rodovia: 'SP-330',
    nomeRodovia: 'Anhanguera',
    km: 'km 145–146',
    sentido: 'Norte',
    alturaAtual: 18,
    limite: 30,
    status: 'normal',
    tipoVegetacao: 'Grama baixa',
    clima: 'Seco — crescimento lento',
    ultimaColeta: '14/06/2026',
    previsaoCorte: '02/07/2026',
    diasAteCorte: 17,
    historico: [
      { data: '02/05', altura: 9 },
      { data: '16/05', altura: 12 },
      { data: '30/05', altura: 15 },
      { data: '14/06', altura: 18 },
    ],
    observacao: null,
  },
  {
    id: '10',
    rodovia: 'SP-348',
    nomeRodovia: 'Bandeirantes',
    km: 'km 76–77',
    sentido: 'Sul',
    alturaAtual: 16,
    limite: 30,
    status: 'normal',
    tipoVegetacao: 'Grama baixa',
    clima: 'Seco — condições normais',
    ultimaColeta: '15/06/2026',
    previsaoCorte: '05/07/2026',
    diasAteCorte: 20,
    historico: [
      { data: '02/05', altura: 8 },
      { data: '16/05', altura: 11 },
      { data: '30/05', altura: 13 },
      { data: '15/06', altura: 16 },
    ],
    observacao: null,
  },
];

export const alertas = [
  {
    id: 'a1',
    trechoId: '1',
    mensagem: 'SP-280 km 42–43 atingiu 34 cm. Corte imediato necessário.',
    tipo: 'Limite atingido',
    data: '13/06/2026',
    lido: false,
  },
  {
    id: 'a2',
    trechoId: '8',
    mensagem: 'SP-160 km 15–16 atingiu 30 cm na Serra do Mar.',
    tipo: 'Limite atingido',
    data: '11/06/2026',
    lido: false,
  },
  {
    id: 'a3',
    trechoId: '3',
    mensagem: 'SP-330 km 98–99 previsto atingir 30 cm em 2 dias.',
    tipo: 'Previsão crítica',
    data: '14/06/2026',
    lido: false,
  },
  {
    id: 'a4',
    trechoId: '5',
    mensagem: 'SP-348 km 88–89 reincidente: 3 ciclos acima de 25 cm.',
    tipo: 'Reincidência',
    data: '15/06/2026',
    lido: true,
  },
];

export const cronograma = [
  {
    id: 'c1',
    trechoId: '1',
    equipe: 'Equipe A',
    dia: 'Segunda, 16/06',
    prioridade: 1,
    status: 'planejado',
  },
  {
    id: 'c2',
    trechoId: '8',
    equipe: 'Equipe B',
    dia: 'Segunda, 16/06',
    prioridade: 2,
    status: 'planejado',
  },
  {
    id: 'c3',
    trechoId: '2',
    equipe: 'Equipe A',
    dia: 'Terça, 17/06',
    prioridade: 3,
    status: 'planejado',
  },
  {
    id: 'c4',
    trechoId: '3',
    equipe: 'Equipe C',
    dia: 'Terça, 17/06',
    prioridade: 4,
    status: 'planejado',
  },
  {
    id: 'c5',
    trechoId: '5',
    equipe: 'Equipe B',
    dia: 'Quarta, 18/06',
    prioridade: 5,
    status: 'planejado',
  },
];

// Funções auxiliares simples
export function corDoStatus(status) {
  if (status === 'corte_necessario') return '#D64545';
  if (status === 'atencao') return '#F2B705';
  return '#1F9D66';
}

export function labelDoStatus(status) {
  if (status === 'corte_necessario') return 'Corte Necessário';
  if (status === 'atencao') return 'Atenção';
  return 'Normal';
}

export function fundoDoStatus(status) {
  if (status === 'corte_necessario') return '#FDECEA';
  if (status === 'atencao') return '#FFF8E1';
  return '#E8F6EF';
}

export function getTrechoPorId(id) {
  return trechos.find((t) => t.id === id);
}
